"""Shared city list for location detection in the mock providers.

Deliberately a curated list (precision over recall): unrecognized locations
are simply left unextracted rather than guessed at. Roles demoing the product
predominantly run in GCC/EMEA/APAC hubs with remote-friendly options.
"""

from __future__ import annotations

CITIES: tuple[str, ...] = (
    # GCC / Middle East
    "dubai",
    "abu dhabi",
    "sharjah",
    "ajman",
    "riyadh",
    "jeddah",
    "dammam",
    "khobar",
    "doha",
    "manama",
    "kuwait city",
    "muscat",
    "amman",
    "beirut",
    "tel aviv",
    "cairo",
    "alexandria",
    "casablanca",
    "tunis",
    "algiers",
    # Europe
    "london",
    "manchester",
    "edinburgh",
    "dublin",
    "berlin",
    "munich",
    "frankfurt",
    "vienna",
    "zurich",
    "geneva",
    "paris",
    "lyon",
    "madrid",
    "barcelona",
    "lisbon",
    "milan",
    "rome",
    "bologna",
    "amsterdam",
    "rotterdam",
    "brussels",
    "stockholm",
    "oslo",
    "copenhagen",
    "helsinki",
    "warsaw",
    "prague",
    "budapest",
    "athens",
    "kyiv",
    "istanbul",
    # Africa
    "lagos",
    "abuja",
    "nairobi",
    "accra",
    "johannesburg",
    "cape town",
    # Asia
    "karachi",
    "lahore",
    "islamabad",
    "mumbai",
    "pune",
    "delhi",
    "gurugram",
    "noida",
    "bengaluru",
    "bangalore",
    "hyderabad",
    "chennai",
    "kolkata",
    "kochi",
    "colombo",
    "dhaka",
    "kathmandu",
    "singapore",
    "kuala lumpur",
    "jakarta",
    "manila",
    "bangkok",
    "ho chi minh",
    "hanoi",
    "hong kong",
    "shanghai",
    "beijing",
    "shenzhen",
    "taipei",
    "seoul",
    "tokyo",
    "osaka",
    # Americas / Oceania
    "new york",
    "san francisco",
    "los angeles",
    "chicago",
    "boston",
    "austin",
    "seattle",
    "denver",
    "dallas",
    "houston",
    "miami",
    "atlanta",
    "toronto",
    "vancouver",
    "montreal",
    "mexico city",
    "sao paulo",
    "buenos aires",
    "sydney",
    "melbourne",
    "auckland",
)
