"""Screening-question generation and persistence.

Questions are generated by the configured LLM provider (or the deterministic
mock), grounded in the match result: strongest matched skills, honest gap
probes for missing must-haves, and seniority-calibrated behavioral questions.
Regenerating replaces the previous set for that application.
"""

from __future__ import annotations

import logging

from sqlalchemy import select
from sqlalchemy.orm import Session, selectinload

from app.ai.base import LLMProvider
from app.core.errors import ValidationAppError
from app.models.application import Application
from app.models.screening import ScreeningQuestion
from app.services import pipeline
from app.services.matching import evaluate_pair

logger = logging.getLogger("talentflow.screening")


def generate_for_application(
    db: Session, application_id: int, *, provider: LLMProvider
) -> list[ScreeningQuestion]:
    """Generate (and persist) a fresh set of screening questions."""
    application = pipeline.get_application(db, application_id)
    result = evaluate_pair(db, application.candidate, application.job)

    matched: list[str] = []
    missing: list[str] = []
    for evaluation in result.requirements:
        if evaluation.kind != "must_have" or evaluation.category != "skill" or not evaluation.skill:
            continue
        if evaluation.status in ("met", "partial"):
            matched.append(evaluation.skill)
        elif evaluation.status == "missing":
            missing.append(evaluation.skill)

    drafts = provider.generate_screening_questions(
        job_title=application.job.title,
        candidate_name=application.candidate.full_name,
        years_experience=application.candidate.years_experience,
        matched_skills=matched,
        missing_skills=missing,
        seniority=application.job.seniority,
    )
    if not drafts:
        raise ValidationAppError("No screening questions were generated — try again.")

    for existing in list(application.screening_questions):
        db.delete(existing)
    db.flush()

    stored: list[ScreeningQuestion] = []
    for index, draft in enumerate(drafts):
        question = ScreeningQuestion(
            application_id=application.id,
            category=draft.category,
            question=draft.question,
            rationale=draft.rationale,
            source=provider.name,
            order_index=index,
        )
        db.add(question)
        stored.append(question)
    db.commit()
    for question in stored:
        db.refresh(question)

    logger.info(
        "screening questions generated",
        extra={
            "application_id": application.id,
            "count": len(stored),
            "provider": provider.name,
        },
    )
    return stored


def list_for_application(db: Session, application_id: int) -> list[ScreeningQuestion]:
    """Stored questions for one application (empty list when none yet)."""
    pipeline.get_application(db, application_id)  # 404 when missing
    return list(
        db.execute(
            select(ScreeningQuestion)
            .where(ScreeningQuestion.application_id == application_id)
            .order_by(ScreeningQuestion.order_index)
        ).scalars()
    )


def list_applications_with_questions(db: Session, *, limit: int = 100) -> list[Application]:
    """Applications that currently have a stored question set (for the page)."""
    statement = (
        select(Application)
        .where(Application.screening_questions.any())
        .options(selectinload(Application.candidate), selectinload(Application.job))
        .order_by(Application.updated_at.desc())
        .limit(max(1, min(limit, 200)))
    )
    return list(db.execute(statement).scalars())
