"""initial schema

Revision ID: 3dc9b96a8fcf
Revises: 
Create Date: 2026-09-28 15:51:35.654310
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa

from app.models.embedding import EmbeddingVector


revision = '3dc9b96a8fcf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    is_postgres = bind.dialect.name == "postgresql"
    if is_postgres:
        # pgvector powers semantic search on the PostgreSQL path (ADR 0004).
        op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('headline', sa.String(length=300), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('years_experience', sa.Float(), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('github_url', sa.String(length=500), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('resume_filename', sa.String(length=300), nullable=True),
    sa.Column('resume_path', sa.String(length=1000), nullable=True),
    sa.Column('resume_text', sa.Text(), nullable=True),
    sa.Column('extraction_method', sa.String(length=30), nullable=False),
    sa.Column('extraction_model', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidates'))
    )
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.create_index('ix_candidates_full_name', ['full_name'], unique=False)

    op.create_table('embedding_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_type', sa.String(length=20), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('embedder', sa.String(length=120), nullable=False),
    sa.Column('embedding', EmbeddingVector(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_embedding_records')),
    sa.UniqueConstraint('owner_type', 'owner_id', 'chunk_index', name=op.f('uq_embedding_records_owner_type'))
    )
    with op.batch_alter_table('embedding_records', schema=None) as batch_op:
        batch_op.create_index('ix_embedding_records_owner', ['owner_type', 'owner_id'], unique=False)

    if is_postgres:
        # ANN index for cosine similarity search (pgvector HNSW).
        op.execute(
            "CREATE INDEX IF NOT EXISTS ix_embedding_records_embedding_hnsw "
            "ON embedding_records USING hnsw (embedding vector_cosine_ops)"
        )

    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('employment_type', sa.String(length=40), nullable=False),
    sa.Column('seniority', sa.String(length=40), nullable=True),
    sa.Column('domain', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('description_text', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('extraction_method', sa.String(length=30), nullable=False),
    sa.Column('extraction_model', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags')),
    sa.UniqueConstraint('name', name=op.f('uq_tags_name'))
    )
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('fk_applications_candidate_id_candidates'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_applications_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_applications')),
    sa.UniqueConstraint('candidate_id', 'job_id', name=op.f('uq_applications_candidate_id'))
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_applications_candidate_id'), ['candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_job_id'), ['job_id'], unique=False)

    op.create_table('candidate_certifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('issuer', sa.String(length=200), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('fk_candidate_certifications_candidate_id_candidates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidate_certifications'))
    )
    with op.batch_alter_table('candidate_certifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidate_certifications_candidate_id'), ['candidate_id'], unique=False)

    op.create_table('candidate_educations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('institution', sa.String(length=300), nullable=True),
    sa.Column('degree', sa.String(length=200), nullable=True),
    sa.Column('field_of_study', sa.String(length=200), nullable=True),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('fk_candidate_educations_candidate_id_candidates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidate_educations'))
    )
    with op.batch_alter_table('candidate_educations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidate_educations_candidate_id'), ['candidate_id'], unique=False)

    op.create_table('candidate_experiences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('fk_candidate_experiences_candidate_id_candidates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidate_experiences'))
    )
    with op.batch_alter_table('candidate_experiences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidate_experiences_candidate_id'), ['candidate_id'], unique=False)

    op.create_table('candidate_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('author', sa.String(length=120), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('fk_candidate_notes_candidate_id_candidates'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_candidate_notes_job_id_jobs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidate_notes'))
    )
    with op.batch_alter_table('candidate_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidate_notes_candidate_id'), ['candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidate_notes_job_id'), ['job_id'], unique=False)

    op.create_table('candidate_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('normalized_name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('fk_candidate_skills_candidate_id_candidates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidate_skills')),
    sa.UniqueConstraint('candidate_id', 'normalized_name', name=op.f('uq_candidate_skills_candidate_id'))
    )
    with op.batch_alter_table('candidate_skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidate_skills_candidate_id'), ['candidate_id'], unique=False)

    op.create_table('candidate_tags',
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('fk_candidate_tags_candidate_id_candidates'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_candidate_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('candidate_id', 'tag_id', name=op.f('pk_candidate_tags'))
    )
    op.create_table('job_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('normalized_skill', sa.String(length=120), nullable=True),
    sa.Column('min_years', sa.Float(), nullable=True),
    sa.Column('keywords', sa.String(length=500), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_requirements_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_requirements'))
    )
    with op.batch_alter_table('job_requirements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_requirements_job_id'), ['job_id'], unique=False)

    op.create_table('pipeline_stage_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('from_stage', sa.String(length=20), nullable=True),
    sa.Column('to_stage', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_pipeline_stage_events_application_id_applications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pipeline_stage_events'))
    )
    with op.batch_alter_table('pipeline_stage_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pipeline_stage_events_application_id'), ['application_id'], unique=False)

    op.create_table('screening_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_screening_questions_application_id_applications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_screening_questions'))
    )
    with op.batch_alter_table('screening_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_screening_questions_application_id'), ['application_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('screening_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_screening_questions_application_id'))

    op.drop_table('screening_questions')
    with op.batch_alter_table('pipeline_stage_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pipeline_stage_events_application_id'))

    op.drop_table('pipeline_stage_events')
    with op.batch_alter_table('job_requirements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_requirements_job_id'))

    op.drop_table('job_requirements')
    op.drop_table('candidate_tags')
    with op.batch_alter_table('candidate_skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidate_skills_candidate_id'))

    op.drop_table('candidate_skills')
    with op.batch_alter_table('candidate_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidate_notes_job_id'))
        batch_op.drop_index(batch_op.f('ix_candidate_notes_candidate_id'))

    op.drop_table('candidate_notes')
    with op.batch_alter_table('candidate_experiences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidate_experiences_candidate_id'))

    op.drop_table('candidate_experiences')
    with op.batch_alter_table('candidate_educations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidate_educations_candidate_id'))

    op.drop_table('candidate_educations')
    with op.batch_alter_table('candidate_certifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidate_certifications_candidate_id'))

    op.drop_table('candidate_certifications')
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_applications_job_id'))
        batch_op.drop_index(batch_op.f('ix_applications_candidate_id'))

    op.drop_table('applications')
    op.drop_table('tags')
    op.drop_table('jobs')
    with op.batch_alter_table('embedding_records', schema=None) as batch_op:
        batch_op.drop_index('ix_embedding_records_owner')

    op.drop_table('embedding_records')
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_index('ix_candidates_full_name')

    op.drop_table('candidates')
    # ### end Alembic commands ###
