"use client";

import Link from "next/link";
import { useState } from "react";

import { api, ApiError } from "@/lib/api";
import { useApi } from "@/hooks/useApi";
import { Badge } from "@/components/ui/Badge";
import { Button } from "@/components/ui/Button";
import { InlineError, LoadingBlock } from "@/components/ui/States";
import type { ApplicationBrief, ScreeningQuestion } from "@/lib/types";

const CATEGORY_ORDER = ["technical", "gap_probe", "experience", "behavioral"];

const CATEGORY_STYLES: Record<string, string> = {
  technical: "bg-sky-50 text-sky-700 ring-sky-200",
  gap_probe: "bg-amber-50 text-amber-800 ring-amber-200",
  experience: "bg-violet-50 text-violet-700 ring-violet-200",
  behavioral: "bg-emerald-50 text-emerald-700 ring-emerald-200",
};

export function ScreeningPanel({ applications }: { applications: ApplicationBrief[] }) {
  const [selectedId, setSelectedId] = useState<number | null>(
    applications.length > 0 ? applications[0].id : null,
  );
  const [questions, setQuestions] = useState<ScreeningQuestion[] | null>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const { data: stored, loading, reload } = useApi(
    () => (selectedId ? api.screening.forApplication(selectedId) : Promise.resolve([])),
    [selectedId],
  );

  const shown = questions ?? stored ?? [];

  async function generate() {
    if (!selectedId) return;
    setBusy(true);
    setError(null);
    try {
      const generated = await api.screening.generate(selectedId);
      setQuestions(generated);
      reload();
    } catch (err) {
      setError(err instanceof ApiError ? err.message : "Could not generate questions.");
    } finally {
      setBusy(false);
    }
  }

  function handleSelect(id: number) {
    setSelectedId(id);
    setQuestions(null);
  }

  if (applications.length === 0) {
    return (
      <p className="text-sm text-slate-400">
        Add this candidate to a job pipeline to generate screening questions.
      </p>
    );
  }

  const grouped = CATEGORY_ORDER.map((category) => ({
    category,
    items: shown.filter((question) => question.category === category),
  })).filter((group) => group.items.length > 0);
  const uncategorized = shown.filter((question) => !CATEGORY_ORDER.includes(question.category));

  return (
    <div className="space-y-4">
      <div className="flex flex-wrap items-center gap-2">
        <select
          aria-label="Application"
          value={selectedId ?? ""}
          onChange={(event) => handleSelect(Number(event.target.value))}
          className="rounded-lg border-0 bg-white px-2.5 py-1.5 text-xs shadow-sm ring-1 ring-inset ring-slate-300"
        >
          {applications.map((application) => (
            <option key={application.id} value={application.id}>
              {application.job_title} · {application.stage}
            </option>
          ))}
        </select>
        <Button size="sm" onClick={generate} loading={busy}>
          {shown.length > 0 ? "Regenerate" : "Generate questions"}
        </Button>
      </div>

      {error ? <InlineError message={error} /> : null}

      {loading && !shown.length ? (
        <LoadingBlock lines={3} />
      ) : shown.length === 0 ? (
        <p className="text-sm text-slate-500">
          No questions yet for this application — generate candidate-specific questions grounded in
          the match results.
        </p>
      ) : (
        <ul className="space-y-3">
          {[...grouped.flatMap((group) => group.items), ...uncategorized].map((question) => (
            <li key={question.id} className="rounded-lg bg-slate-50 px-3 py-2.5">
              <div className="mb-1 flex items-center gap-2">
                <Badge className={CATEGORY_STYLES[question.category] ?? "bg-slate-100 text-slate-600 ring-slate-200"}>
                  {question.category.replace("_", " ")}
                </Badge>
                <span className="text-[11px] text-slate-400">
                  generated by {question.source === "mock" ? "mock rules" : "OpenAI"}
                </span>
              </div>
              <p className="text-sm text-slate-800">{question.question}</p>
              {question.rationale ? (
                <p className="mt-1 text-xs italic text-slate-500">{question.rationale}</p>
              ) : null}
            </li>
          ))}
        </ul>
      )}

      <p className="text-[11px] text-slate-400">
        Never includes questions about protected characteristics.{" "}
        <Link href="/screening" className="text-indigo-600 hover:underline">
          All question sets →
        </Link>
      </p>
    </div>
  );
}
