"""Seed the database with the synthetic demo dataset.

The demo exercises the REAL pipeline: JDs go through job extraction, resume
files (PDF/DOCX/TXT) are ingested through document extraction and structured
extraction, applications move through the real pipeline service (with audit
trail), and screening questions are generated by the configured provider.

Usage:
    cd backend && uv run python -m app.seed            # seed (skips if present)
    cd backend && uv run python -m app.seed --reset    # wipe + reseed (dev only)
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from sqlalchemy import func, select

from app.ai.factory import build_embedding_provider, build_llm_provider
from app.core.config import get_settings
from app.core.logging import configure_logging
from app.db.session import SessionLocal
from app.models import (
    Application,
    Candidate,
    CandidateCertification,
    CandidateEducation,
    CandidateExperience,
    CandidateNote,
    CandidateSkill,
    EmbeddingRecord,
    Job,
    JobRequirement,
    PipelineStageEvent,
    ScreeningQuestion,
    Tag,
)
from app.models.tag import candidate_tags
from app.seed.demo_candidates import APPLICATION_PLAN, CANDIDATES, NOTE_PLAN, TAG_PLAN
from app.seed.demo_jobs import DEMO_JOBS
from app.seed.generate_files import generate_demo_files
from app.services import candidate_service, job_service, pipeline
from app.services import screening as screening_service

#: repo root: backend/app/seed/run_seed.py -> parents[3]
REPO_ROOT = Path(__file__).resolve().parents[3]

_STAGE_SEQUENCES: dict[str, list[str]] = {
    "NEW": ["NEW"],
    "SCREENING": ["NEW", "SCREENING"],
    "SHORTLISTED": ["NEW", "SCREENING", "SHORTLISTED"],
    "INTERVIEW": ["NEW", "SCREENING", "SHORTLISTED", "INTERVIEW"],
    "OFFER": ["NEW", "SCREENING", "SHORTLISTED", "INTERVIEW", "OFFER"],
    "HIRED": ["NEW", "SCREENING", "SHORTLISTED", "INTERVIEW", "OFFER", "HIRED"],
    "REJECTED": ["NEW", "REJECTED"],
}


def run_migrations() -> None:
    """Apply pending migrations so seeding works on a fresh database."""
    from alembic import command
    from alembic.config import Config

    backend_dir = Path(__file__).resolve().parents[2]
    config = Config(str(backend_dir / "alembic.ini"))
    config.set_main_option("script_location", str(backend_dir / "alembic"))
    command.upgrade(config, "head")


def wipe(db) -> None:
    """Delete all rows (dependency order) — dev/demo only."""
    for table in (
        ScreeningQuestion.__table__,
        PipelineStageEvent.__table__,
        Application.__table__,
        CandidateNote.__table__,
        candidate_tags,
        Tag.__table__,
        CandidateSkill.__table__,
        CandidateCertification.__table__,
        CandidateEducation.__table__,
        CandidateExperience.__table__,
        Candidate.__table__,
        EmbeddingRecord.__table__,
        JobRequirement.__table__,
        Job.__table__,
    ):
        db.execute(table.delete())


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="app.seed", description=__doc__)
    parser.add_argument("--reset", action="store_true", help="wipe existing data first")
    args = parser.parse_args(argv)

    configure_logging("INFO")
    settings = get_settings()
    run_migrations()

    db = SessionLocal()
    try:
        if args.reset:
            wipe(db)
            db.commit()
            print("Wiped existing data (--reset).")

        existing_jobs = db.scalar(select(func.count(Job.id))) or 0
        if existing_jobs and not args.reset:
            print(
                f"Database already contains {existing_jobs} job(s) — nothing to do.\n"
                "Run with --reset to rebuild the demo dataset."
            )
            return 0

        llm = build_llm_provider(settings)
        embeddings = build_embedding_provider(settings)
        print(f"AI provider : {llm.name} ({llm.model})")
        print(f"Embeddings  : {embeddings.name} ({embeddings.model})")
        print(f"Database    : {settings.sqlalchemy_url.split('@')[-1]}")

        files = generate_demo_files(REPO_ROOT)
        print(
            f"Demo files  : {len(files['jobs'])} JDs, {len(files['resumes'])} resumes in examples/"
        )

        jobs: dict[str, Job] = {}
        for slug, job_data in DEMO_JOBS.items():
            jobs[slug] = job_service.create_job(
                db,
                title="",
                jd_text=job_data["text"],
                company=job_data["company"],
                provider=llm,
                embedding_provider=embeddings,
            )
        print(f"Jobs        : created {len(jobs)}")

        candidates: dict[str, Candidate] = {}
        for candidate_data, path in zip(CANDIDATES, files["resumes"], strict=False):
            candidate = candidate_service.ingest_resume(
                db,
                filename=path.name,
                data=path.read_bytes(),
                provider=llm,
                embedding_provider=embeddings,
                upload_dir=settings.upload_dir,
            )
            candidates[candidate_data["full_name"]] = candidate
        print(f"Candidates  : ingested {len(candidates)}")

        applications: dict[tuple[str, str], Application] = {}
        for name, slug, target_stage, note in APPLICATION_PLAN:
            candidate = candidates[name]
            application = pipeline.create_application(
                db, candidate_id=candidate.id, job_id=jobs[slug].id
            )
            sequence = _STAGE_SEQUENCES[target_stage]
            for index, stage in enumerate(sequence[1:], start=1):
                is_final = index == len(sequence) - 1
                pipeline.move_stage(
                    db,
                    application.id,
                    to_stage=stage,
                    note=(note if is_final and note else f"Moved to {stage.title()} (demo seed)"),
                )
            applications[(name, slug)] = pipeline.get_application(db, application.id)
        print(f"Applications: {len(applications)} across the pipeline")

        for name, tag_name, color in TAG_PLAN:
            candidate_service.add_tag(db, candidates[name].id, name=tag_name, color=color)

        for name, slug, author, body in NOTE_PLAN:
            candidate_service.add_note(
                db,
                candidates[name].id,
                body=body,
                author=author,
                job_id=jobs[slug].id if slug else None,
            )

        for name, slug in (
            ("Amira Haddad", "senior-full-stack-engineer"),
            ("Omar Al Farsi", "devops-engineer"),
        ):
            application = applications[(name, slug)]
            questions = screening_service.generate_for_application(db, application.id, provider=llm)
            print(f"Screening   : {len(questions)} questions for {name}")

        counts = {
            "jobs": db.scalar(select(func.count(Job.id))) or 0,
            "candidates": db.scalar(select(func.count(Candidate.id))) or 0,
            "applications": db.scalar(select(func.count(Application.id))) or 0,
            "notes": db.scalar(select(func.count(CandidateNote.id))) or 0,
            "tags": db.scalar(select(func.count(Tag.id))) or 0,
        }
        print("\nDemo dataset ready:")
        for key, value in counts.items():
            print(f"  {key:<13} {value}")
        print("\nStart the app and open the dashboard to explore it.")
        return 0
    finally:
        db.close()


if __name__ == "__main__":
    sys.exit(main())
